# Generated by Django 5.0.2 on 2025-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='favourite',
        ),
        migrations.AddField(
            model_name='location',
            name='is_favourited',
            field=models.BooleanField(default=False),
        ),
    ]
