# Generated by Django 5.0.7 on 2025-02-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_location_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
    ]
