# Generated by Django 5.1.6 on 2025-02-14 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activation_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
