# Generated by Django 5.0.2 on 2025-02-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_activation_code'),
        ('booking', '0009_booking_activation_code'),
    ]

    operations = [
    ]
