# Generated by Django 5.0.2 on 2025-02-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_merge_20250216_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='activation_code',
        ),
    ]
