# Generated by Django 5.0.2 on 2025-02-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_location_rating'),
        ('booking', '0012_booking_activation_code'),
    ]

    operations = [
    ]
