# Generated by Django 5.1.6 on 2025-02-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_merge_20250216_1832'),
        ('booking', '0013_merge_20250216_1841'),
    ]

    operations = [
    ]
