# Generated by Django 5.0.2 on 2025-02-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_merge_20250216_1832'),
        ('booking', '0013_merge_20250216_1841'),
    ]

    operations = [
    ]
