# Generated by Django 5.1.6 on 2025-02-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_merge_20250216_2010'),
        ('booking', '0014_merge_20250222_2053'),
    ]

    operations = [
    ]
