# Generated by Django 5.0.2 on 2025-02-22 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_merge_20250222_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
