# Generated by Django 5.0.2 on 2025-02-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_location_like_count_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
