# Generated by Django 5.1.6 on 2025-02-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_location_rating'),
        ('booking', '0016_alter_location_rating'),
    ]

    operations = [
    ]
