# Generated by Django 5.0.2 on 2025-02-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_location_rating'),
        ('booking', '0018_like'),
    ]

    operations = [
    ]
