# Generated by Django 5.1.6 on 2025-02-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_merge_20250223_1921'),
        ('booking', '0019_merge_0016_alter_location_rating_0018_like'),
    ]

    operations = [
    ]
