<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-02 16:34
=======
# Generated by Django 5.0.2 on 2025-03-02 15:12
>>>>>>> origin/develop

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('booking', '0020_merge_20250302_1701'),
=======
        ('booking', '0020_merge_20250302_1615'),
>>>>>>> origin/develop
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='booking.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'location')},
            },
        ),
    ]
