# Generated by Django 5.1.6 on 2025-03-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_merge_20250223_1955'),
        ('booking', '0020_merge_20250302_1701'),
    ]

    operations = [
    ]
