# Generated by Django 5.0.2 on 2025-03-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_location_favourite_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='favourite',
            field=models.CharField(default='fa-solid fa-heart-circle-plus', max_length=100),
        ),
    ]
