# Generated by Django 5.0.2 on 2025-03-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_alter_location_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_favourited',
            field=models.BooleanField(default=False),
        ),
    ]
