# Generated by Django 5.0.2 on 2025-03-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_location_is_favourited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='favourite',
        ),
    ]
